version: '3.4'

services:
  dashboard:
    container_name: opensergo-dashboard
    image: joao/opensergo-dashboard
    volumes:
      - mycompsvc_home:/home    
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    networks:
      - traefik_network
    ports:
      - 3210:8080
# kitex:
#     container_name: ld-kitex
#     image: joao/kitex
#     volumes:
#       - mycompsvc_home:/home
#     user: jovyan
#     build:
#       context: .
#       dockerfile: ./kitex/Dockerfile
#     networks:
#       - traefik_network
  database:
    container_name: opensergo-database
    image: joao/opensergo-database
    build: 
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: d0ck3r
      MYSQL_DATABASE: opensergo
    depends_on:
      - dashboard
    volumes:
      - mycompsvc_db:/var/lib/mysql:rw
      - mycompsvc_home:/home
      - ./mycompsvc_home/opensergo-dashboard/opensergo-dashboard-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "3306:3306"
    networks:
      - traefik_network

volumes:
  mycompsvc_home:
  mycompsvc_db:
    
  
networks:
  traefik_network:
    external: true
