version: '3.4'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ufu123
    networks:
      - traefik_network
    restart: on-failure
    ports:
      - 8080:8080
      - 8443:8443

networks:
  traefik_network:
    external: true