version: '3.4'

services:
  coredns:
    container_name: ufu-coredns
    image: joao/coredns:1.10.1
    networks:
      - devnet
    ports:
      - 53:53
      - 53:53/udp

    volumes:
      - /home/learning-docker/coredns/config:/etc/coredns


networks:
  devnet:
    external: true
