version: '3.4'

services:
  httpproxy:
    image: httpproxy
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - devnet
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

networks:
  devnet:
    external: true