version: '3.4'

services:
  gnuoctave:
    image: joao/gnuoctave
    volumes:
      - octave_home:/home
    user: jovyan
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  octave_home: