name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Workdir
      run: pwd; ls -l
      
    - name: Build the Docker image
      run: docker build kea-dhcp/server --tag kea-dhcp:$(date +%s)
